### ISSUE TITLE
Error when executing against incoming file

### ISSUE THREAD

**Issue by sfunk1x** [mdhiggins/radarr-sma#14]
I'm encountering an issue with both sonarr-sma and radarr-sma when the sma script is called:

```
2020-10-23 17:19:46 - RadarrPostProcess - INFO - Radarr extra script post processing started.
2020-10-23 17:19:46 - resources.readsettings - INFO - /usr/local/sma/venv/bin/python3
2020-10-23 17:19:46 - resources.readsettings - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.
2020-10-23 17:19:46 - resources.mediaprocessor - INFO - File /home/unprivilegeduser/store/video/testVideo/testVideo.mkv is not valid
2020-10-23 17:19:46 - RadarrPostProcess - INFO - Processing returned False.
2020-10-23 17:19:46 - RadarrPostProcess - ERROR - Error processing file
Traceback (most recent call last):
  File "/usr/local/sma/postRadarr.py", line 210, in <module>
    sys.exit(1)
SystemExit: 1
```

Looking at the postRadarr.py file, the issue isn't apparent to me. I'm able to execute non-docker sma from the CLI normally and the file is processed and converted as expected. My system host has the nvidia device, and the nvidia-smi docker container is running and executes as expected.

My docker-compose.yml is as follows:

```
  radarr:
    container_name: radarr
    build:
      context: https://github.com/mdhiggins/radarr-sma.git#build
      args:
        - ffmpeg_tag=4.3.1-nvidia1804
    volumes:
      - /home/unprivilegeduser/.config/Radarr:/config
      - /media/4tbarray/video:/4tbvideo
      - /home/unprivilegeduser/workspace/docker-mediaserver:/usr/local/sma/config
    ports:
      - 8385:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SMA_PATH=/usr/local/sma
      - SMA_UPDATE=true
    restart:
      always
```

I can't seem to attach the autoProcess.ini, so I've included what I believe is relevant here:

```
[Converter]
ffmpeg = /usr/local/bin/ffmpeg
ffprobe = /usr/local/bin/ffprobe
threads = 0
hwaccels = dxva2, cuvid, qsv, d3d11va
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv, h264_qsv
output-directory =
output-format = mp4
output-extension = mp4
temp-extension =
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to =
move-to =
delete-original = True
sort-streams = True
process-same-extensions = False
force-convert = False
post-process = False
preopts =
postopts =
hwdevices = vaapi:/dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi
wait-post-process = False
detailed-progress = True

[Permissions]
chmod = 0755
uid = 1000
gid = 1000

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = eng
download-artwork = poster
sanitize-disposition =

[Video]
codec = h264, x264
max-bitrate = 0
crf = -1
crf-profiles =
max-width = 0
profile =
max-level = 0.0
pix-fmt =
filter =
force-filter = False
preset =
codec-parameters =
dynamic-parameters = False

[Audio]
codec = aac
languages =
default-language =
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 320
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter =
sample-rates =
copy-original = True
aac-adtstoasc = False
ignore-truehd = mp4, m4v
force-filter = False
ignored-dispositions =
unique-dispositions = False

[Universal Audio]
codec = aac
channel-bitrate = 0
first-stream-only = False
move-after = False
filter =
force-filter = False

[Subtitle]
codec = mov_text
codec-image-based =
languages =
default-language =
first-stream-of-language = False
encoding =
burn-subtitles = False
burn-dispositions =
download-subs = False
download-hearing-impaired-subs = False
download-providers =
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
attachment-codec =
ignored-dispositions =
unique-dispositions = False

[Sonarr]
host = 127.0.0.1
port = 8989
apikey = redacted
ssl = False
webroot =
force-rename = False

[Radarr]
host = 127.0.0.1
port = 7878
apikey = redacted
ssl = False
webroot =
force-rename = False
```

Any help here would be appreciated!
