### ISSUE TITLE
Build version need updating?

### ISSUE THREAD

**Issue by Zeusy123** [mdhiggins/radarr-sma#29]
I just did a build using #build as I need fdkaac in ffmpeg and the radarr version is:
3.0.2.4552
—
Feb 5 2021

Any way to update the radarr in this docker to latest version keeping the compiled ffmpeg?

**Comment by mdhiggins** [comment]
The build version pulls from other sources it's not a precompiled image

**Comment by mdhiggins** [comment]
Let me clarify, the build tag is meant to be built, you should NOT be pulling down that 8 month old image but instead building it yourself

**Comment by Zeusy123** [comment]
Thanks you so much once again bro.  Im still learning dockers.
All i want to get is latest versions of sonarr & radarr with your brilliant automator encoding on ffmepg with fdkaac enabled.

Im even trying your latest stable build wihch doesnt have fdkacc enabled in ffmpeg, and trying to rebuild ffmpeg within its console:(

**Comment by mdhiggins** [comment]
I believe the jrottenberg builds that are used in the `build` tag should include libfdkaac by default, so you were on the right track using that tag just need to config it to build locally instead of using that old image

Instead of a typical configuration which would like this (using docker-compose as my example since that's what I use)
```
  sonarr:
    image: mdhiggins/sonarr-sma:develop
    container_name: sonarr
    volumes:
      - /opt/appdata/sonarr:/config
      - /opt/appdata/sma:/usr/local/sma/config
      - /mnt/storage/tv:/tv
      - /mnt/storage/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
```

It should look like this

```
  sonarr:
    build:
      context: https://github.com/mdhiggins/sonarr-sma.git#build
      args:
        - ffmpeg_tag=ubuntu2004
    container_name: sonarr
    volumes:
      - /opt/appdata/sonarr:/config
      - /opt/appdata/sma:/usr/local/sma/config
      - /mnt/storage/tv:/tv
      - /mnt/storage/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
```

And then you just run `docker-compose build` before you run `docker-compose up -d`
