### ISSUE TITLE
build version not starting

### ISSUE THREAD

**Issue by eikowagenknecht** [mdhiggins/radarr-sma#33]
Since Synology unfortunately disabled external devices (ans with that VAAPI support) for their web UI for good (previously they could be used by exporting, modifying and importing the json config) I'm in the process of switching to a docker-composed version of this repository.

my docker-compose.yml:

```
version: "2.1"
services:
  sonarr:
    container_name: sonarr
    build:
      context: /volume1/configs/repos/sonarr # this is a git pulled https://github.com/mdhiggins/sonarr-sma.git#build
      args:
        ffmpeg_tag: 4.4-vaapi2004
    environment:
      - PUID=1028
      - PGID=65536
      - TZ=Europe/Berlin
      - MAX_NAME=143 # File length for encrypted file system
    volumes:
      - /volume1/configs/sma_sonarr:/usr/local/sma/config
      - /volume1/downloads/complete:/downloads
      - /volume1/serien:/tv
      - /volume1/configs/sonarr:/config
    ports:
      - 38004:8989/tcp
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    network_mode: bridge
```

This built fine, though there were some warnings (red text) logged: 
[build_log.txt](https://github.com/mdhiggins/radarr-sma/files/8048675/build_log.txt)

It also seems to start up, but keeps hanging there with lots of errors in the sonarr.txt log:
[sonarr.txt](https://github.com/mdhiggins/radarr-sma/files/8048687/sonarr.txt)
 
console errors  have a liitle bit more to say (Temporary failure resolving 'download.mono-project.com' etc.):
[console_error.log](https://github.com/mdhiggins/radarr-sma/files/8048808/console_error.log)

It mostly seems to complain about missing permissions for /etc and `System.DllNotFoundException: sqlite3`.

Do you have any idea what could be going wrong here? It worked fine before using the prebuilt image with the same options.

**Comment by mdhiggins** [comment]
Hm not 100% sure what's going on here, seems to be more of a Sonarr problem none of which is handled by my docker container but instead by the parent linuxserver container

Couple things I would try

1. Use the remote context to see if this makes any different (instead of your git pulled source)
2. Try and temporarily unmount your /config folder, this will rule out database corruption with your existing library
3. Include a sonarr_tag in your args and use the develop branch (ffmpeg_tag and sonarr_tag branches should be on the same linux version, and currently the latest/stable branch is still on 1804 so its a mismatch with your vaapi2004 tag)
4. Try and build the linuxserver/sonarr container from source and see if that works, if that gives the same error then its probably a parent container problem

Let me know if any of these things provide any insight

**Comment by eikowagenknecht** [comment]
Thanks for taking the time to support me here :-)

1. Unfortunately I can't do that because it only leads to an OpenSSL error as discussed in https://stackoverflow.com/questions/66579446/error-executing-docker-compose-building-webserver-unable-to-prepare-context-un and the linked issues
```
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: /var/packages/Git/target/libexec/git-core/git-remote-https: /tmp/_MEInYQBlh/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /lib64/libcurl.so.4)
: exit status 128
```

2. Same error without mounted configs dir.

3. Good catch, added the version tag and rebuilt. Unfortunately still the same "temporary failure resolving ..." errors and even more mono related errors :-(

4. Also throws lots of errors, not the "Temporary failure resolving" but mono related :-(

Guess I'll have to follow this upstream to the linuxserver repo..

**Comment by eikowagenknecht** [comment]
As a workaround I'm using it with the following docker-compose now (eikowagenknecht/... image is built on my desktop instead of synology) and it seems to work just fine:

```
version: "2.1"
services:
  sonarr:
    container_name: sonarr
    image: eikowagenknecht/sonarr-sma-vaapi:latest
    environment:
      - PUID=1028
      - PGID=65536
      - TZ=Europe/Berlin
      - MAX_NAME=143 # File length for encrypted file system
    volumes:
      - /volume1/configs/sma_sonarr:/usr/local/sma/config
      - /volume1/downloads/blackhole:/blackhole # Not in mdhiggins image
      - /volume1/downloads/complete:/downloads
      - /volume1/serien:/tv
      - /volume1/configs/sonarr:/config
    ports:
      - 38004:8989/tcp
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    network_mode: bridge
```
