### ISSUE TITLE
Hardware encoding failure

### ISSUE THREAD

**Issue by TravisRoy** [mdhiggins/radarr-sma#43]
Latest update is causing hardware encoding to fail. Was working fine before update with same docker compose.

```
FFmpeg command:
======================
/usr/bin/ffmpeg -hwaccel vaapi -i "Dunkirk (2017) - Remux-1080p.mkv" -vcodec hevc_vaapi -map 0:0 -field_order progressive -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -preset slower -tag:v hvc1 -qp 28 -vaapi_device /dev/dri/renderD128 -vf "format=nv12|vaapi,hwupload" -c:a:0 ac3 -map 0:1 -ac:a:0 6 -b:a:0 1536k -metadata:s:a:0 BPS=1536000 -metadata:s:a:0 BPS-eng=1536000 -metadata:s:a:0 "title=5.1 Channel" -metadata:s:a:0 "handler_name=5.1 Channel" -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y "/media/merged/Media/NEW-Movies/Dunkirk (2017)/Dunkirk (2017) - Remux-1080p.mp4"
======================
[                    ] 0% Error converting file, FFMPEG error.
Traceback (most recent call last):
  File "/usr/local/sma/resources/mediaprocessor.py", line 2292, in convert
    for timecode, debug in conv:
  File "/usr/local/sma/converter/__init__.py", line 329, in convert
    for timecode, debug in self.ffmpeg.convert(outfile,
  File "/usr/local/sma/converter/ffmpeg.py", line 795, in convert
    raise FFMpegConvertError('Exited with code %d' % p.returncode, cmd,
converter.ffmpeg.FFMpegConvertError: <unprintable FFMpegConvertError object>
/usr/bin/ffmpeg -hwaccel vaapi -i Dunkirk (2017) - Remux-1080p.mkv -vcodec hevc_vaapi -map 0:0 -field_order progressive -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -preset slower -tag:v hvc1 -qp 28 -vaapi_device /dev/dri/renderD128 -vf format=nv12|vaapi,hwupload -c:a:0 ac3 -map 0:1 -ac:a:0 6 -b:a:0 1536k -metadata:s:a:0 BPS=1536000 -metadata:s:a:0 BPS-eng=1536000 -metadata:s:a:0 title=5.1 Channel -metadata:s:a:0 handler_name=5.1 Channel -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f mp4 -threads 0 -metadata:g encoding_tool=SMA -y /media/merged/Media/NEW-Movies/Dunkirk (2017)/Dunkirk (2017) - Remux-1080p.mp4
ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r3) 20220924
  configuration: --prefix=/usr --enable-avfilter --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libpulse --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-lto --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-librist --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --disable-lzma --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --enable-libdrm --enable-libzmq --optflags=-O2 --disable-debug --enable-libsvtav1
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[AVHWDeviceContext @ 0x7ff39c638e40] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument

There was an error processing file Dunkirk (2017) - Remux-1080p.mkv, no output data received
```

Docker Compose:

```
  radarr-sma:
    image: mdhiggins/radarr-sma
    container_name: radarr-sma
    volumes:
      - /plexms/docker/radarr-sma/opt/appdata/radarr:/config
      - /plexms/docker/radarr-sma/opt/appdata/sma:/usr/local/sma/config
      - /plexms/docker/radarr-sma/mnt/storage/movies:/movies
      - /media/merged:/media/merged
      - /home/travis/docker/sabnzbd-sma/downloads:/downloads #optional
      - /data:/media/data
      - /home/travis/docker/shared:/shared
    ports:
      - 7879:7878
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr|linuxserver/mods:universal-package-install
      - SMA_USE_REPO=true
      - INSTALL_PACKAGES=libva-intel-driver|mesa-dri-gallium
      - INSTALL_PIP_PACKAGES=tmdbsimple|guessit|mutagen|qtfaststart
    devices:
      - /dev/dri:/dev/dri
```
