### ISSUE TITLE
ffmpeg not using gpu

### ISSUE THREAD

**Issue by almontasser** [mdhiggins/radarr-sma#53]
I'm trying to use VAAPI as described in the README, it do convert the files, however not using the gpu (Intel integrated gpu), it uses the cpu. I don't know if I do something wrong.

And isn't using QSV would be better?

Here is my docker compose:

```yaml
  radarr:
    build:
      context: https://github.com/mdhiggins/radarr-sma.git
      args:
        - ffmpeg_tag=4.4-vaapi2004
    container_name: radarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT:-.}/radarr:/config
      - ${DATA_ROOT}:/data
      - ${CONFIG_ROOT:-.}/radarr/sma:/usr/local/sma/config
    restart: always
    devices: 
      - "/dev/dri:/dev/dri"
```
